export {default as Cart} from './Cart/Cart'
export {default as Home} from './Home/Home'
export {default as LoginPage} from './Login/LoginPage'
export {default as RegistrerPages} from './Login/RegistrerPages'
export {default as Pizza} from './Pizza/Pizza'
